feat(router): add v2 api for /fingerprint
juspay/hyperswitch-card-vault pull request #119
Opened 2024-09-26 14:02 UTC by ShankarSinghC

add v2 api for /fingerprint

2024-09-27 10:08 UTC, Chethan-rao approved these changes

2024-09-27 11:01 UTC, NishantJoshi00 commented on src/storage/db.rs
> +        let fingerprint_hash = algo.encode(data.expose().into_bytes())?;
can we change the definition of encode

```diff
- impl<const N: usize> Encode<Vec<u8>, Vec<u8>> for HmacSha512<N> {
+ impl<const N: usize> Encode<Secret<Vec<u8>>, Secret<Vec<u8>>> for HmacSha512<N> {
    type ReturnType<T> = Result<T, error::ContainerError<error::CryptoError>>;

-    fn encode(&self, input: Vec<u8>) -> Self::ReturnType<Vec<u8>> {
+    fn encode(&self, input: Secret<Vec<u8>>) -> Self::ReturnType<Secret<Vec<u8>>> {
        let key = hmac::Key::new(ring::hmac::HMAC_SHA512, self.0.peek());

```

2024-09-27 15:09 UTC, NishantJoshi00 requested changes

2024-09-27 15:09 UTC, NishantJoshi00 commented on src/storage/db.rs
> +        let algo = HmacSha512::<1>::new(key.expose().into_bytes().into());
Secret supports map operator

2024-09-27 15:09 UTC, NishantJoshi00 commented on src/storage/db.rs
> +        let algo = HmacSha512::<1>::new(key.expose().into_bytes().into());
https://github.com/juspay/hyperswitch/blob/main/crates/masking/src/secret.rs#L75

2024-09-27 15:09 UTC, NishantJoshi00 commented on src/storage/db.rs
> +            .find_by_fingerprint_hash(fingerprint_hash.clone().expose().as_slice().into())
Same here

2024-09-28 08:05 UTC, Chethan-rao requested changes

2024-09-28 08:05 UTC, Chethan-rao commented on src/storage/db.rs
> +            .find_by_fingerprint_hash(fingerprint_hash.clone().map(|inner| inner))
```suggestion
            .find_by_fingerprint_hash(fingerprint_hash.clone())
```

2024-09-28 08:23 UTC, NishantJoshi00 approved these changes

2024-09-28 10:19 UTC, Chethan-rao approved these changes

2024-09-30 10:01 UTC, merged