feat(router): add v2 api for /delete
juspay/hyperswitch-card-vault pull request #121
Opened 2024-09-27 12:17 UTC by ShankarSinghC

add v2 api for /delete

2024-09-28 14:31 UTC, Chethan-rao requested changes

2024-09-28 14:31 UTC, Chethan-rao commented on src/routes/data.rs
> +pub use super::routes_v2;
```suggestion
use super::routes_v2;
```

2024-09-28 14:31 UTC, Chethan-rao commented on src/routes/data.rs
> +
This will be under `/data/v2`. Is this fine?

CC: @NishantJoshi00

2024-09-28 14:31 UTC, Chethan-rao commented on src/routes/routes_v2/data/types.rs
> +}
Do we need this Status? I think the HTTP status code itself is sufficient

2024-09-28 14:31 UTC, Chethan-rao commented on src/storage/storage_v2.rs
> +    /// Fetch payment data from vault table by decrypting with `dek`
Please change the comment. Don't include any domain related things in v2

2024-09-28 14:31 UTC, Chethan-rao commented on src/storage/storage_v2.rs
> +    /// Insert payment data from vault table by decrypting with `dek`
Same here

2024-09-28 14:31 UTC, Chethan-rao commented on src/storage/storage_v2.rs
> +    /// Delete card from the vault, without access to the `dek`
Same here

2024-09-28 14:31 UTC, Chethan-rao commented on src/storage/storage_v2.rs
> +    // ) -> Result<Option<types::Vault>, ContainerError<Self::Error>>;
Can be removed?

2024-09-28 14:31 UTC, Chethan-rao commented on src/storage/storage_v2/db.rs
> +    type Error = error::LockerDBError;
Can we rename these Errors too as per v2

2024-09-28 14:31 UTC, Chethan-rao commented on src/storage/storage_v2/types.rs
> +}
These are already defined in `v1` types. No need to define here again

2024-09-28 17:59 UTC, Chethan-rao requested changes

2024-09-28 17:59 UTC, Chethan-rao commented on src/app.rs
> +        "api/v2/vault",
```suggestion
        "/api/v2/vault",
```

2024-09-28 17:59 UTC, Chethan-rao commented on src/storage/storage_v2.rs
> +    /// Insert data from vault table
```suggestion
    /// Insert data into vault table
```

2024-09-28 18:28 UTC, Chethan-rao approved these changes

2024-09-30 05:14 UTC, NishantJoshi00 reviewed
This looks good, but i am not comfortable merging TODOs in the main branch, can we put them under v2 feature flag? Or at least let's wait for @Chethan-rao to raise a PR to this branch.

2024-10-04 10:52 UTC, NishantJoshi00 approved these changes

2024-10-04 10:52 UTC, merged