refactor(key_manager): integrate key manager in vault apis
juspay/hyperswitch-card-vault pull request #124
Opened 2024-10-04 11:35 UTC by Chethan-rao

2024-10-09 06:48 UTC, NishantJoshi00 requested changes

2024-10-09 06:48 UTC, NishantJoshi00 commented on src/crypto/keymanager/internal_keymanager.rs
> +            .map(|inner| -> Box<dyn CryptoOperationsManager> { Box::new(inner) })?)
```suggestion
            .map(Box::new)?)
```

2024-10-09 06:48 UTC, NishantJoshi00 commented on src/crypto/keymanager/internal_keymanager.rs
> +            .map(|inner| -> Box<dyn CryptoOperationsManager> { Box::new(inner) })?;
same here

2024-10-09 06:48 UTC, NishantJoshi00 commented on src/routes/data/crypto_operation.rs
> +    locker.enc_data = decrypted_data;
This increases the changes of data inconsistency. I am worried that if this function isn't called we might deal with encrypted data everywhere and we wouldn't know. Worst case the opposite might happen.

Should we consider investing some time on using something like.

```rust
enum Encryptable {
    Encrypted(Secret<Vec<u8>>),
    Plaintext(StrongSecret<String>)
}
```

2024-10-09 06:48 UTC, NishantJoshi00 commented on src/storage.rs
> +    #[allow(dead_code)]
Why dead code though? can the lint be handled with `cfg` feature flags?

2024-10-09 06:48 UTC, NishantJoshi00 commented on src/storage/caching.rs
> +impl<T> CacheableWithEntity<T> for T {}
Nice one dude!

2024-10-09 06:48 UTC, NishantJoshi00 commented on src/storage/consts.rs
> +    pub const AUTHORIZATION: &str = "Authorization";
funny enough both of these might not be required.

- [`AUTHORIZATION`](https://docs.rs/hyper/latest/hyper/header/constant.AUTHORIZATION.html)
- [`CONTENT_TYPE`](https://docs.rs/hyper/latest/hyper/header/constant.CONTENT_TYPE.html)

2024-10-09 06:48 UTC, NishantJoshi00 commented on src/storage/db.rs
> +            .map(|inner| inner.into())
```
.map_or_else(From::from, From::from)
```
This is just a nit, not something to worry over

2024-10-09 06:48 UTC, NishantJoshi00 commented on src/storage/utils.rs
> +    uuid::Uuid::new_v4().to_string()
Should we invest efforts in going with [`UUIDv7`](https://uuid7.com/)

2024-10-09 12:36 UTC, NishantJoshi00 approved these changes
Looks good, can you please attach some screenshots as the changes in the key manager are merged.

2024-10-09 14:12 UTC, NishantJoshi00 approved these changes

2024-10-10 04:41 UTC, ShankarSinghC approved these changes

2024-10-10 12:15 UTC, merged