feat(caching): implement hash_table and merchant table caching
juspay/hyperswitch-card-vault pull request #55
Opened 2023-12-08 06:57 UTC by NishantJoshi00

## Description

Implement Caching for the following tables
- Merchant
- Hash Table

Properties of cache implemented
- The cache is implement by [`moka`](https://docs.rs/moka/latest/moka/) and only consists of IMC and not a shared cache. 
- The cache is implemented on tables where no delete/update operations will take place

2023-12-08 07:48 UTC, Chethan-rao requested changes

2023-12-08 07:48 UTC, Chethan-rao commented on src/config.rs
> +
These configs are not added in toml?

2023-12-08 09:34 UTC, Chethan-rao submitted a review, later dismissed

2024-01-29 11:18 UTC, ShankarSinghC approved these changes

2024-01-29 11:32 UTC, Chethan-rao approved these changes

2024-01-29 11:42 UTC, merged