feat(health): add deep health check with support for diagnostics
juspay/hyperswitch-card-vault pull request #64
Opened 2023-12-26 12:12 UTC by NishantJoshi00

## Description

Adding support for deep health-check for the application

2023-12-26 13:22 UTC, Chethan-rao requested changes

2023-12-26 13:22 UTC, Chethan-rao commented on src/routes/health.rs
> +}
put this under `key_custodian` feature flag

2023-12-26 13:22 UTC, Chethan-rao commented on src/routes/health.rs
> +pub struct Custodian;
put this under `key_custodian` feature flag

2023-12-27 08:15 UTC, Chethan-rao approved these changes

2023-12-27 14:39 UTC, Chethan-rao commented on src/routes/health.rs
> +        crate::logger::info!("Health was called");
No need of logging this again as its already logged in health API handler

2024-02-05 11:03 UTC, dracarys18 submitted a review, later dismissed

2024-02-12 06:04 UTC, dracarys18 approved these changes

2024-02-12 06:05 UTC, merged