fix: address non-digit character cases in card number validation
juspay/hyperswitch-card-vault pull request #93
Opened 2024-05-13 16:36 UTC by Chethan-rao

This PR addresses the non-digit character cases in card number validation and raises an appropriate error if fails. 
This PR also includes min and max length check for card number.

2024-05-13 16:46 UTC, NishantJoshi00 requested changes
Don't modify the existing function create a different fallible function and then cascade the existing one with that one using something like and_then

2024-05-13 16:51 UTC, Chethan-rao commented
> Don't modify the existing function, create a different fallible function and then cascade the existing one with that one using something like and_then

We'll anyway have to modify the current function for card number length constraint. So why don't we do it on that itself. 
Also I think its better we rename the `luhn_on_string` function to something like `validate_card_number` as this function does more validation including the luhn validation?

2024-05-13 17:26 UTC, SanchithHegde reviewed
> [...] Also I think its better we rename the `luhn_on_string` function to something like `validate_card_number` as this function does more validation in which luhn being one validation?

+1

Should we also consider storing the sanitized card number (without whitespaces) in the database, or do we have the need to store the original value received in the request body?

2024-05-13 17:26 UTC, SanchithHegde commented on src/validations.rs
> +const MIN_CARD_NUMBER_LENGTH: usize = 12;
Can we add doc comments for this?

2024-05-13 17:26 UTC, SanchithHegde commented on src/validations.rs
>  #[allow(clippy::expect_used)]
Let's move this `allow` annotation above that specific line/expression please.

2024-05-13 17:26 UTC, SanchithHegde commented on src/validations.rs
> +        .try_fold(Vec::with_capacity(20), |mut data, character| {
We can maybe use the `MAX_CARD_NUMBER_LENGTH` const for specifying the capacity?

```suggestion
        .try_fold(Vec::with_capacity(MAX_CARD_NUMBER_LENGTH), |mut data, character| {
```

2024-05-13 17:33 UTC, Chethan-rao commented
> > [...] Also I think its better we rename the `luhn_on_string` function to something like `validate_card_number` as this function does more validation in which luhn being one validation?
> 
> +1
> 
> Should we also consider storing the sanitized card number (without whitespaces) in the database, or do we have the need to store the original value received in the request body?

I think for card number its fine to store the sanitized version

2024-05-13 19:00 UTC, SanchithHegde submitted a review, later dismissed

2024-05-13 22:12 UTC, NishantJoshi00 commented
Yes, but lets look at in the following way.
1. Sanitization of the data
2. Length validation
3. Luhn check

Then, won't it make sense to have the code formulated like this:

```rust
let card_number = "4242 4242 4242 4242";

fn sanitize_card_number(card_number: &str) -> Result<CardNumber> {
    Ok(card_number)
        .and_then(validate_length)
        .and_then(validate_chars)
        .and_then(luhn_on_string)
        .map(CardNumber)
}
```

Something like this, here the responsibility of each function is clear. 
1. validate_length (could be a closure): Only validates the card length
2. validate_chars: currently, being done in the `luhn_on_string`
3. luhn_on_string: performs luhn check on any string given, or better yet, discard the function and use the internal function `luhn` on `&[u8]`
4. And finally, wrapping it into the `CardNumber` type or any strong secret that we need

2024-05-14 09:30 UTC, Chethan-rao commented
> Sure, it makes sense, but I was thinking something on the lines of:
> 
> 1. Sanitization of the data
> 2. Length validation
> 3. Luhn check
> 
> Then, won't it make sense to have the code formulated like this:
> 
> ```rust
> let card_number = "4242 4242 4242 4242";
> 
> fn sanitize_card_number(card_number: &str) -> Result<CardNumber> {
>     Ok(card_number)
>         .and_then(validate_length)
>         .and_then(validate_chars)
>         .and_then(luhn_on_string)
>         .map(CardNumber)
> }
> ```
> 
> Something like this, here the responsibility of each function is clear.
> 
> 1. validate_length (could be a closure): Only validates the card length
> 2. validate_chars: currently, being done in the `luhn_on_string`
> 3. luhn_on_string: performs luhn check on any string given, or better yet, discard the function and use the internal function `luhn` on `&[u8]`
> 4. And finally, wrapping it into the `CardNumber` type or any strong secret that we need
> 
> By changing the name of the function we are just giving the function more responsibility, instead of splitting it between multiple dependent component.

Sure I have created multiple functions for each validation and are being called in `sanitize_card_number` function

2024-05-14 10:27 UTC, SanchithHegde approved these changes

2024-05-14 20:44 UTC, NishantJoshi00 approved these changes

2024-05-14 20:44 UTC, NishantJoshi00 commented on src/validations.rs
> +    Ok(is_card_number_valid)
```suggestion
    Ok(card_number.as_str())
        .and_then(validate_card_number_chars)
        .and_then(validate_card_number_length)
        .map(|number| luhn(&number))
```

2024-05-14 20:44 UTC, NishantJoshi00 commented on src/validations.rs
> +    Ok(is_card_number_valid)
But, this looks very clean... good stuff!

2024-05-15 07:45 UTC, merged